### ISSUE TITLE
ER database schema

### ISSUE THREAD

**Issue by alikon** [nadeeshaan/JGSoC-SQL-Optimisation#1]
Create the ER database schema of tables related to the #__content table

**Comment by nadeeshaan** [comment]
![capture](https://cloud.githubusercontent.com/assets/1329674/3074026/e2addfae-e31d-11e3-9452-2caf4ef8107a.PNG)
Added the missing relations

----Modified Database schema for content table
![capture](https://cloud.githubusercontent.com/assets/1329674/3077549/9d7cdd42-e433-11e3-8659-a759706536e0.PNG)

**Comment by alikon** [comment]
There are other relations not reported 
as an example 

#_content.id <-> #_ucm_content.core_content_item_id

**Comment by alikon** [comment]
ok, set as 80% waiting for Gunjan review

**Comment by gunjanpatel** [comment]
@alikon Looks fine for me. Thanks @nadeeshaan
