### ISSUE TITLE
Report schema design issues

### ISSUE THREAD

**Issue by alikon** [nadeeshaan/JGSoC-SQL-Optimisation#2]
A list of the potential issues on the database design

**Comment by nadeeshaan** [comment]
- Type Incompatibilities can be found in the tables in which there are relations. This will be an disadvantage if using join operations
- Cannot find for what purpose the #__ucm_base table is used.
  *If #__ucm_base table is used for multiple language support mapping then there is a many to many relationship and will have to add another table for the m to m relationship
